package com.falcon.furniture.furniture.model;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Furniture")
public class Furniture {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String  name;

    @DynamoDBAttribute
    private Double price;

    @DynamoDBAttribute
    private String colour;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private Integer warrantyPeriod;

    @DynamoDBAttribute
    private String modelId;

}
